"""
Reconstruye `fif-loy-cl-cg-discovery.temporal.campaigns_redemption_metrics`
desde 2025-01-01 hasta ayer, con el fix en la tabla B del CTE TIPO_CANJEADOR
para eliminar los casos "NO INFO".

Fix: la tabla B estaba hardcodeada a los últimos 2 meses de CURRENT_DATE.
     Para backfills históricos se necesita cargar todos los cierres de mes
     desde el inicio del período procesado.

Uso:
    python rebuild_campaigns_table.py
    python rebuild_campaigns_table.py --inicio 2025-01-01
"""
import sys, time, argparse
sys.stdout = open(sys.stdout.fileno(), mode='w', buffering=1)

from google.cloud import bigquery

PROJECT_CONSUMPTION = "fif-loy-cl-consumption"
PROJECT_DISCOVERY   = "fif-loy-cl-cg-discovery"
TABLE_TARGET        = f"`{PROJECT_DISCOVERY}.temporal.campaigns_redemption_metrics`"

client = bigquery.Client(project=PROJECT_DISCOVERY)


def run_script(sql: str, label: str = ""):
    print(f"\n{'='*70}")
    print(f"  {label}")
    print(f"{'='*70}")
    t0 = time.time()
    job = client.query(sql)
    print(f"  Job ID: {job.job_id}")
    print("  Esperando...", flush=True)
    job.result()          # bloquea hasta que termina
    elapsed = time.time() - t0
    print(f"  Completado en {elapsed/60:.1f} min")
    if job.errors:
        print(f"  ERRORES: {job.errors}")
    return job


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--inicio", default="2025-01-01")
    args = parser.parse_args()
    inicio = args.inicio

    print(f"\nReconstruyendo {TABLE_TARGET}")
    print(f"Período: {inicio} → ayer (CURRENT_DATE - 1)")
    print("ATENCIÓN: esto puede tardar varios minutos según el volumen de datos.")

    sql = f"""
DECLARE INICIO DATE DEFAULT '{inicio}';
DECLARE FIN    DATE DEFAULT DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY);

CREATE OR REPLACE TABLE {TABLE_TARGET}
PARTITION BY FECHA_ENVIO
OPTIONS(description="Tabla con base de clientes de trigger vencimientos")
AS

WITH CLIENTES AS (
  SELECT
    CUST_ID,
    CASE
      WHEN cust_active_cmr_flg = 'Y' AND cust_active_deb_flg = 'N' THEN 'BANCO'
      WHEN cust_active_cmr_flg = 'N' AND cust_active_deb_flg = 'Y' THEN 'BANCO'
      WHEN cust_active_cmr_flg = 'Y' AND cust_active_deb_flg = 'Y' THEN 'BANCO'
      WHEN cust_active_omp_flg = 'Y' THEN 'OMP'
    END AS TIPO_CLIENTE,
    CUST_STOCK_POINT_AMT
  FROM `{PROJECT_CONSUMPTION}.svw_fif_loy_cl_datalake_prod__trf_loy_cl_prd.svw_clients_entity`
  WHERE PARTITION_DATE = FIN
),

PRIMER_CANJE AS (
  SELECT
    CUST_ID,
    MIN(REDEMPTION_DATE) PRIMER_CANJE
  FROM `{PROJECT_CONSUMPTION}.control_de_gestion.frozen_redemption_entity`
  WHERE RETURN_FLAG IS FALSE
  GROUP BY ALL
),

INFO_CANJE AS (
  SELECT
    REDEMPTION_DATE,
    CUST_ID,
    BU_CHANNEL_NAME,
    COUNT(REDEMPTION_ID_UNICO) CANJES,
    SUM(REDEMPTION_POINTS_AMT) PUNTOS_CANJEADOS
  FROM `{PROJECT_CONSUMPTION}.control_de_gestion.frozen_redemption_entity`
  WHERE REDEMPTION_DATE BETWEEN INICIO AND FIN AND RETURN_FLAG IS FALSE
  GROUP BY ALL
),

TIPO_CANJEADOR AS (

  WITH BASE AS (
    SELECT
      A.PARTITION_DATE,
      B.PARTITION_DATE PARTITION_CIERRE,
      A.CUST_ID,
      A.TIPO_CLIENTE,
      A.TIPO_CLIENTE_USO,
      A.LOY_CATEGORIA,
      B.LOY_CATEGORIA LOY_CATEGORIA_CIERRE,
      A.FLAG_ACUMULADOR,
      A.FLAG_ACUMULADOR_FALABELLA,
      A.FLAG_ACUMULADOR_DIG_3P,
      A.FLAG_ACUMULADOR_TOTTUS,
      A.FLAG_ACUMULADOR_SODIMAC,
      A.FLAG_ACUMULADOR_FCOM,
      A.FLAG_ACUMULADOR_IKEA,
      A.FLAG_ACUMULADOR_ONTHEM,
      B.FLAG_ACUMULADOR FLAG_ACUMULADOR_CIERRE,
      A.FLAG_POS_CANJE_12_24M FLAG_POS_CANJE,
      B.FLAG_POS_CANJE_12_24M FLAG_POS_CANJE_CIERRE,
      A.FLAG_CANJEADOR_12_24M FLAG_CANJEADOR,
      B.FLAG_CANJEADOR_12_24M FLAG_CANJEADOR_CIERRE,
      A.ULTIMA_COMPRA ULTIMA_COMPRA,
      B.ULTIMA_COMPRA ULTIMA_COMPRA_CIERRE,
      A.ULTIMA_FECHA_POS_CANJE ULTIMA_POS_CANJE,
      B.ULTIMA_FECHA_POS_CANJE ULTIMA_POS_CANJE_CIERRE,
      A.ULTIMO_CANJE,
      B.ULTIMO_CANJE ULTIMO_CANJE_CIERRE
    FROM (
      SELECT * FROM `{PROJECT_CONSUMPTION}.funnel_clientes.clients_funnel`
      WHERE PARTITION_DATE >= INICIO
    ) A
    LEFT JOIN (
      -- FIX: carga TODOS los cierres de mes desde el inicio del período,
      --      no solo los 2 meses relativos a CURRENT_DATE.
      SELECT * FROM `{PROJECT_CONSUMPTION}.funnel_clientes.clients_funnel`
      WHERE PARTITION_DATE >= DATE_SUB(DATE_TRUNC(INICIO, MONTH), INTERVAL 1 DAY)
        AND DATE_SUB(DATE_TRUNC(DATE_ADD(PARTITION_DATE, INTERVAL 1 DAY), MONTH), INTERVAL 1 DAY) = PARTITION_DATE
    ) B
    ON A.CUST_ID = B.CUST_ID
    AND DATE_SUB(DATE_TRUNC(A.PARTITION_DATE, MONTH), INTERVAL 1 DAY) = B.PARTITION_DATE
  ),

  TIPO_ACUMULADOR_1 AS (
    SELECT
      *,
      CASE
        WHEN ((FLAG_ACUMULADOR_CIERRE = 0 AND ULTIMA_COMPRA_CIERRE IS NULL)
            AND (FLAG_ACUMULADOR = 1 AND ULTIMA_COMPRA IS NOT NULL))
            OR (FLAG_ACUMULADOR = 1 AND PARTITION_CIERRE IS NULL AND PARTITION_DATE IS NOT NULL
               AND FLAG_ACUMULADOR_CIERRE IS NULL) THEN "NUEVO"
        WHEN ULTIMA_COMPRA_CIERRE IS NOT NULL AND FLAG_ACUMULADOR_CIERRE = 0 AND FLAG_ACUMULADOR = 1 THEN "RECUPERADO"
        WHEN FLAG_ACUMULADOR_CIERRE = 1 AND FLAG_ACUMULADOR = 0 THEN "FUGADOS"
        WHEN ULTIMA_COMPRA IS NULL THEN "NO_PARTICIPANTE_HISTORICO"
        WHEN FLAG_ACUMULADOR_CIERRE = 0 AND FLAG_ACUMULADOR = 0 AND ULTIMA_COMPRA IS NOT NULL THEN "NO_PARTICIPANTE_ACTUAL"
        WHEN FLAG_ACUMULADOR = 1 AND FLAG_ACUMULADOR_CIERRE = 1 AND ULTIMA_COMPRA IS NOT NULL THEN "RECURRENTE"
      END TIPO_ACUMULADOR
    FROM BASE
  ),

  TIPO_ACUMULADOR_2 AS (
    SELECT
      *,
      CASE
        WHEN TIPO_ACUMULADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(PARTITION_DATE, MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(PARTITION_DATE, MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_1M"
        WHEN TIPO_ACUMULADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 1 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 1 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_2M"
        WHEN TIPO_ACUMULADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 2 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 2 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_3M"
        WHEN TIPO_ACUMULADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 5 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 5 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_6M"
        WHEN TIPO_ACUMULADOR = "FUGADOS"
          AND (((UPPER(LOY_CATEGORIA_CIERRE) = "ELITE" OR UPPER(LOY_CATEGORIA_CIERRE) = "PREMIUM") AND UPPER(LOY_CATEGORIA) = "NORMAL"
              AND ULTIMA_COMPRA < DATE_SUB(PARTITION_DATE,INTERVAL 12 MONTH))
            OR ((UPPER(LOY_CATEGORIA_CIERRE) = "ELITE" OR UPPER(LOY_CATEGORIA_CIERRE) = "PREMIUM") AND UPPER(LOY_CATEGORIA) = "FAN"
              AND ULTIMA_COMPRA < DATE_SUB(PARTITION_DATE,INTERVAL 12 MONTH)))
          THEN "FUGADO_POR_CATEGORIA"
        WHEN TIPO_ACUMULADOR = "FUGADOS"
          AND ((UPPER(LOY_CATEGORIA_CIERRE) = UPPER(LOY_CATEGORIA))
            OR (UPPER(LOY_CATEGORIA_CIERRE) IN("NORMAL","FAN") AND UPPER(LOY_CATEGORIA) IN("NORMAL","FAN"))
            OR (UPPER(LOY_CATEGORIA_CIERRE) IN ("ELITE","PREMIUM") AND UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM")))
          THEN "FUGADO_POR_COMPRA"
        ELSE TIPO_ACUMULADOR
      END TIPO_ACUMULADOR_DETALLADO
    FROM TIPO_ACUMULADOR_1
  ),

  TIPO_CANJEADOR_1 AS (
    SELECT
      *,
      CASE
        WHEN ((FLAG_ACUMULADOR_CIERRE = 0 OR FLAG_CANJEADOR_CIERRE = 0 AND ULTIMO_CANJE_CIERRE IS NULL)
            AND (FLAG_ACUMULADOR = 1 AND FLAG_CANJEADOR = 1 AND ULTIMO_CANJE IS NOT NULL))
            OR (FLAG_ACUMULADOR = 1 AND PARTITION_CIERRE IS NULL AND PARTITION_DATE IS NOT NULL
               AND FLAG_CANJEADOR = 1 AND FLAG_CANJEADOR_CIERRE IS NULL) THEN "NUEVO"
        WHEN (ULTIMA_COMPRA_CIERRE IS NOT NULL AND ULTIMO_CANJE_CIERRE IS NOT NULL)
            AND FLAG_CANJEADOR_CIERRE = 0 AND FLAG_CANJEADOR = 1 AND FLAG_ACUMULADOR = 1 THEN "RECUPERADO"
        WHEN (FLAG_ACUMULADOR_CIERRE = 1 AND FLAG_CANJEADOR_CIERRE = 1 AND FLAG_ACUMULADOR = 0)
            OR (FLAG_ACUMULADOR_CIERRE = 1 AND FLAG_CANJEADOR_CIERRE = 1 AND FLAG_CANJEADOR = 0) THEN "FUGADOS"
        WHEN ULTIMO_CANJE IS NULL THEN "NO_CANJEADOR_HISTORICO"
        WHEN FLAG_CANJEADOR_CIERRE = 0 AND FLAG_CANJEADOR = 0 AND ULTIMO_CANJE IS NOT NULL THEN "NO_CANJEADOR_FUNNEL"
        WHEN (FLAG_ACUMULADOR = 0) AND FLAG_CANJEADOR = 1 THEN "CANJEADOR_NO_PARTICIPANTE"
        WHEN (FLAG_ACUMULADOR_CIERRE = 0) AND FLAG_CANJEADOR_CIERRE = 1 AND FLAG_CANJEADOR = 0 THEN "EX_CANJEADOR_NO_PARTICIPANTE"
        WHEN FLAG_ACUMULADOR = 1 AND FLAG_ACUMULADOR_CIERRE = 1
          AND FLAG_CANJEADOR = 1 AND FLAG_CANJEADOR_CIERRE = 1
          AND ULTIMO_CANJE IS NOT NULL AND ULTIMA_COMPRA IS NOT NULL THEN "RECURRENTE"
      END TIPO_CANJEADOR
    FROM TIPO_ACUMULADOR_2
  ),

  TIPO_CANJEADOR_2 AS (
    SELECT
      * EXCEPT (FLAG_ACUMULADOR_IKEA, FLAG_ACUMULADOR_DIG_3P),
      CASE
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(PARTITION_DATE, MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(PARTITION_DATE, MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_COMPRA_1M"
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(PARTITION_DATE, MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(PARTITION_DATE, MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_CANJE_1M"
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 1 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 1 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_COMPRA_2M"
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 1 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 1 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_CANJE_2M"
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 2 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 2 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_COMPRA_3M"
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 2 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 2 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_CANJE_3M"
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 5 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 5 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_COMPRA_6M"
        WHEN TIPO_CANJEADOR = "RECURRENTE"
          AND ((UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 5 MONTH), MONTH),INTERVAL 24 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMO_CANJE <= DATE_SUB(LAST_DAY(DATE_ADD(PARTITION_DATE, INTERVAL 5 MONTH), MONTH),INTERVAL 12 MONTH)))
          THEN "POSIBLES_FUGADOS_CANJE_6M"
        WHEN TIPO_CANJEADOR = "FUGADOS"
          AND (((UPPER(LOY_CATEGORIA_CIERRE) = "ELITE" OR UPPER(LOY_CATEGORIA_CIERRE) = "PREMIUM") AND UPPER(LOY_CATEGORIA) = "NORMAL"
              AND (ULTIMA_COMPRA < DATE_SUB(PARTITION_DATE,INTERVAL 12 MONTH) OR ULTIMO_CANJE < DATE_SUB(PARTITION_DATE,INTERVAL 12 MONTH)))
            OR ((UPPER(LOY_CATEGORIA_CIERRE) = "ELITE" OR UPPER(LOY_CATEGORIA_CIERRE) = "PREMIUM") AND UPPER(LOY_CATEGORIA) = "FAN"
              AND (ULTIMA_COMPRA < DATE_SUB(PARTITION_DATE,INTERVAL 12 MONTH) OR ULTIMO_CANJE < DATE_SUB(PARTITION_DATE,INTERVAL 12 MONTH))))
          THEN "FUGADO_POR_CATEGORIA"
        WHEN TIPO_CANJEADOR = "FUGADOS"
          AND ((UPPER(LOY_CATEGORIA_CIERRE) = UPPER(LOY_CATEGORIA))
            OR (UPPER(LOY_CATEGORIA_CIERRE) = "NORMAL" AND UPPER(LOY_CATEGORIA) = "FAN")
            OR (UPPER(LOY_CATEGORIA_CIERRE) IN ("ELITE","PREMIUM") AND UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM")))
          AND ((UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMO_CANJE <= DATE_SUB(PARTITION_DATE, INTERVAL 12 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMO_CANJE <= DATE_SUB(PARTITION_DATE, INTERVAL 24 MONTH)))
          THEN "FUGADO_POR_CANJE"
        WHEN TIPO_CANJEADOR = "FUGADOS"
          AND ((UPPER(LOY_CATEGORIA_CIERRE) = UPPER(LOY_CATEGORIA))
            OR (UPPER(LOY_CATEGORIA_CIERRE) IN("NORMAL","FAN") AND UPPER(LOY_CATEGORIA) IN("NORMAL","FAN"))
            OR (UPPER(LOY_CATEGORIA_CIERRE) IN ("ELITE","PREMIUM") AND UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM")))
          AND ((UPPER(LOY_CATEGORIA) IN ("NORMAL","FAN") AND ULTIMA_COMPRA <= DATE_SUB(PARTITION_DATE, INTERVAL 12 MONTH))
            OR (UPPER(LOY_CATEGORIA) IN ("ELITE","PREMIUM") AND ULTIMA_COMPRA <= DATE_SUB(PARTITION_DATE, INTERVAL 24 MONTH)))
          THEN "FUGADO_POR_COMPRA"
        ELSE TIPO_CANJEADOR
      END TIPO_CANJEADOR_DETALLADO,
      FLAG_ACUMULADOR_IKEA,
      FLAG_ACUMULADOR_DIG_3P
    FROM TIPO_CANJEADOR_1
  )

  SELECT PARTITION_DATE, CUST_ID, TIPO_CANJEADOR FROM TIPO_CANJEADOR_2
),

NOMBRE_CAMPANHA AS (
  SELECT
    a.id_jobenvio,
    a.fecha_sent,
    a.fecha_real,
    a.email_cliente,
    b.DESC_EMAILNAME
  FROM `{PROJECT_CONSUMPTION}.acc_loy_cl_datalake.vw_svw_acc_ftcad_cl_omm_prod_vw_acc_omm_cm_mail` a
  LEFT JOIN `{PROJECT_CONSUMPTION}.acc_loy_cl_datalake.vw_svw_acc_ftcad_cl_omm_prod_vw_acc_omm_cm_jobenvio` b
    ON a.id_jobenvio = b.id_jobenvio AND a.fecha_real = b.FECHA_REAL
  WHERE a.fecha_real >= INICIO AND b.fecha_real >= INICIO
),

CRUCE_CAMPANHA AS (
  SELECT
    A.NOMBRE_CAMPANHA,
    A.FECHA_ENVIO,
    CASE WHEN B.DESC_EMAILNAME IS NOT NULL THEN 1 ELSE 0 END CRUCE_CAMP
  FROM (SELECT DISTINCT FECHA_ENVIO, NOMBRE_CAMPANHA
        FROM `{PROJECT_CONSUMPTION}.loy_campaigns.historical_campaigns`) A
  LEFT JOIN (SELECT DISTINCT FECHA_SENT, DESC_EMAILNAME FROM NOMBRE_CAMPANHA) B
    ON REPLACE(nombre_campanha, ' ', '') = REPLACE(b.DESC_EMAILNAME, ' ', '')
    AND a.fecha_envio = B.FECHA_SENT
),

CRUCE_SALESFORCE AS (
  SELECT
    A.CANAL,
    A.TIPO_MEDICION,
    A.tipo_campanha,
    a.FECHA_ENVIO,
    a.nombre_campanha,
    b.DESC_EMAILNAME,
    a.TIPO_CLIENTE,
    a.rut RUT_HISTORICAL,
    CASE WHEN b.email_cliente IS NOT NULL THEN a.rut ELSE NULL END RUT_SALESFORCE,
    a.email_corporativo,
    b.email_cliente
  FROM `{PROJECT_CONSUMPTION}.loy_campaigns.historical_campaigns` a
  INNER JOIN NOMBRE_CAMPANHA b
    ON REPLACE(nombre_campanha, ' ', '') = REPLACE(b.DESC_EMAILNAME, ' ', '')
    AND a.email_corporativo = b.email_cliente
    AND a.fecha_envio = B.FECHA_SENT
),

CONSOLIDADO AS (
  SELECT
    a.FECHA_ENVIO,
    a.NOMBRE_CAMPANHA,
    A.RUT,
    A.GMGC,
    A.TIPO_CLIENTE,
    CS.DESC_EMAILNAME DESC_EMAILNAME_CRUCE,
    CS.RUT_SALESFORCE,
    A.INICIO_VIGENCIA,
    A.FIN_VIGENCIA,
    CASE
      WHEN CC.CRUCE_CAMP = 1 AND GMGC = "GM" THEN COALESCE(CS.RUT_SALESFORCE, A.RUT)
      ELSE A.RUT
    END RUT_MEDICION
  FROM `{PROJECT_CONSUMPTION}.loy_campaigns.historical_campaigns` A
  LEFT JOIN CRUCE_SALESFORCE CS
    ON REPLACE(A.nombre_campanha, ' ', '') = REPLACE(CS.DESC_EMAILNAME, ' ', '')
    AND a.email_corporativo = CS.email_cliente
    AND a.fecha_envio = CS.FECHA_ENVIO
  LEFT JOIN CRUCE_CAMPANHA CC
    ON a.nombre_campanha = cc.nombre_campanha AND a.fecha_envio = cc.fecha_envio
  WHERE a.fecha_envio >= INICIO AND a.fecha_envio <= FIN
)

SELECT
  FECHA_ENVIO,
  NOMBRE_CAMPANHA,
  TIPO_CLIENTE,
  CASE WHEN BU_CHANNEL_NAME IS NULL THEN "NO CANJE" ELSE BU_CHANNEL_NAME END CANAL_CANJE,
  GMGC,
  CASE WHEN C.CUST_ID IS NOT NULL THEN "CANJEO" ELSE "NO CANJEO" END FLAG_CANJE,
  CASE WHEN PRIMER_CANJE < FECHA_ENVIO THEN "CANJEADOR HISTORICO" ELSE "NO CANJEADOR HISTORICO" END TIPO,
  CASE
    WHEN F.TIPO_CANJEADOR = "NO_CANJEADOR_HISTORICO" THEN "NO_CANJEADOR_HISTORICO"
    WHEN F.TIPO_CANJEADOR IN ("NO_CANJEADOR_FUNNEL","EX_CANJEADOR_NO_PARTICIPANTE","FUGADOS") THEN "FUGADOS"
    WHEN F.TIPO_CANJEADOR = "NUEVO" THEN "NUEVO"
    WHEN F.TIPO_CANJEADOR = "RECUPERADO" THEN "RECUPERADO"
    WHEN F.TIPO_CANJEADOR IN ("RECURRENTE","CANJEADOR_NO_PARTICIPANTE") THEN "RECURRENTE"
    ELSE "NO INFO"
  END GRUPO_CANJE_PRE,
  CASE
    WHEN G.TIPO_CANJEADOR = "NO_CANJEADOR_HISTORICO" THEN "NO_CANJEADOR_HISTORICO"
    WHEN G.TIPO_CANJEADOR IN ("NO_CANJEADOR_FUNNEL","EX_CANJEADOR_NO_PARTICIPANTE","FUGADOS") THEN "FUGADOS"
    WHEN G.TIPO_CANJEADOR = "NUEVO" THEN "NUEVO"
    WHEN G.TIPO_CANJEADOR = "RECUPERADO" THEN "RECUPERADO"
    WHEN G.TIPO_CANJEADOR IN ("RECURRENTE","CANJEADOR_NO_PARTICIPANTE") THEN "RECURRENTE"
    ELSE "NO INFO"
  END GRUPO_CANJE_POST,
  COUNT(DISTINCT RUT_MEDICION) CLIENTES,
  SUM(canjes) canjes,
  ABS(SUM(PUNTOS_CANJEADOS)) PUNTOS_CANJEADOS
FROM CONSOLIDADO A
LEFT JOIN PRIMER_CANJE B ON A.RUT_MEDICION = B.CUST_ID
LEFT JOIN INFO_CANJE C
  ON A.RUT_MEDICION = C.CUST_ID AND REDEMPTION_DATE BETWEEN INICIO_VIGENCIA AND FIN_VIGENCIA
LEFT JOIN TIPO_CANJEADOR F ON A.RUT_MEDICION = F.CUST_ID AND INICIO_VIGENCIA = F.PARTITION_DATE
LEFT JOIN TIPO_CANJEADOR G ON A.RUT_MEDICION = G.CUST_ID AND FIN_VIGENCIA   = G.PARTITION_DATE
GROUP BY ALL
"""

    run_script(sql, f"Reconstruyendo tabla ({inicio} → ayer)")
    print("\nTabla reconstruida. Ahora actualizando el parquet local...")

    # Actualizar parquet después de reconstruir la tabla
    import subprocess
    subprocess.run(
        ["python3", "extract.py", "--fecha-inicio", inicio],
        cwd=__file__.rsplit("/", 1)[0]
    )


if __name__ == "__main__":
    main()
